### ISSUE TITLE
Add upgrade script

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/paymaster#140]
```[tasklist]
### Tasks
- [x] add a script to upgrade Paymaster
- [x] add tests of the script
- [x] move to ethers v6 and update dependencies
- [x] connect upgrade-tools 3
- [ ] https://github.com/skalenetwork/skale-contracts/issues/69
- [ ] https://github.com/skalenetwork/upgrade-tools/issues/270
- [ ] https://github.com/skalenetwork/upgrade-tools/issues/222
```
